version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=${LOGIN}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - restaurant-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOGIN} -d restaurant"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant
      - SPRING_DATASOURCE_USERNAME=${LOGIN}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD}
    ports:
      - '8080:8080'
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  postgres-data: